# Starter pipeline
trigger:
- dependabot/maven/my-app/junit-junit-4.13.1

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: Maven@2
  inputs:
    mavenPomFile: 'my-app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenFeedAuthenticate: true
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'hillagold/myrepo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  displayName: run
  inputs:
    containerRegistry: dockerhub
    command: 'run hillagold/myrepo:$(Build.BuildId)'
    container: 'hillagold/myrepo'
    tags: '$(Build.BuildId)'
- task: Docker@1
  displayName: run-1
  inputs:
    containerRegistry: dockerhub
    command: 'run'
    container: 'hillagold/myrepo'
    tags: '$(Build.BuildId)'
# - task: Docker@2
#   inputs:
#     containerRegistry: 'dockerhub'
#     tags: '$(Build.BuildId)'
#     command: 'run'
#     container: 'hillagold/myrepo'

