# Starter pipeline
trigger:
- dependabot/maven/my-app/junit-junit-4.13.1

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: Maven@2
  inputs:
    mavenPomFile: 'my-app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenFeedAuthenticate: true
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'hillagold/myrepo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# - task: Docker@2
#   inputs:
#     containerRegistry: 'dockerhub'
#     tags: '$(Build.BuildId)'
#     command: 'start'
#     container: 'hillagold/myrepo'
# - task: DockerCompose@0
#   inputs:
#     containerregistrytype: 'Azure Container Registry'
#     dockerComposeFile: '**/docker-compose.yml'
#     action: 'Run a Docker Compose command'
#     containerCommand: 
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'dockerhub'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'